- .github/workflows/main.yml
- README.md
Reverts openmrs/openmrs-contrib-fhir2-ig#18
> Revert "test CI BUILD"

- input/fsh/omrs-observation.fsh
https://issues.openmrs.org/browse/FM2-500
Added Observation Resource,Profile, Example and Mapping
> Fhir Ig Observation Example, Mappings and Profile

- input/fsh/omrs-commons.fsh
- input/fsh/omrs-diagnosticReport.fsh
- input/fsh/omrs-observation.fsh
- input/fsh/omrs-serviceRequest.fsh
- input/fsh/omrs-terminology.fsh
- input/fsh/omrs.task.fsh
https://issues.openmrs.org/browse/FM2-498
Added Task Resource Profile,Mapping, Example Resource and extensions.
For extensions we wil create their own Pr
Mapping
Example
> OpenMRS Task Resource Profile, Mapping and Example with extensions

- input/fsh/omrs-person.fsh
**Ticket issue** link: https://issues.openmrs.org/browse/FM2-491
**Description:**
1. Created Person Resource Profile 
**Screen Shot**
> Create Openmrs Person Profile

- input/fsh/omrs-practitioner.fsh
**Issue Ticket:** https://issues.openmrs.org/browse/FM2-496
**Description:**
1. Practitioner Profile
3. Practitioner Resource Mapping
5. Example Practitioner Resource (json)
> OMRS Practitioner Resource profile,Mapping and Resource Example

- input/fsh/omrs-patient.fsh
https://issues.openmrs.org/browse/FM2-490
Waiting on this  [PR](https://github.com/openmrs/openmrs-contrib-fhir2-ig/pull/14)  to get merged  then I can proceed with this pr.
> OpenMRS Patient Example and Mappings

- input/fsh/omrs-medication-request.fsh
Ticket Issue: https://issues.openmrs.org/browse/FM2-504
> FM2-504: FHIR IG MedicationRequest Resource Profile, Mapping,Example

- input/fsh/omrs-serviceRequest.fsh
https://issues.openmrs.org/browse/FM2-503  cc @mozzy11  @ibacher  @pmanko  @abertnamanya
> FHIR Service Request Resource, Profile, Mapping, Example resource

- input/fsh/omrs-practitioner.fsh
Ticket Link: https://issues.openmrs.org/browse/FM2-522
> FM2-522: Added Practitioner resource search Parameters docs

- input/fsh/omrs-medication-request.fsh
Ticket Link: https://issues.openmrs.org/browse/FM2-521
> FM2-521: Added MedicationRequest resource search Parameters docs

- input/fsh/omrs-diagnosticReport.fsh
https://issues.openmrs.org/browse/FM2-502  cc @mozzy11 , @ibacher  @pmanko
> FHIR Diagnostic Resource, Profile, Mapping, Example resource

- input/fsh/omrs-allergyIntolerance.fsh
https://issues.openmrs.org/browse/FM2-505
cc  @ibacher  @mozzy11  @pmanko
> FHIR IG Allergy Intolerance Resource, Profile, Mapping and Example Resource

- input/fsh/omrs-group.fsh
Issue Ticket: https://issues.openmrs.org/browse/FM2-510
> FM2-510: FHIR IG Group Resource Profile, Example

- input/fsh/omrs.task.fsh
Ticket Link: https://issues.openmrs.org/browse/FM2-520
> FM2-520: Made changes in the Task profile and example then created the search parameters docs

- input/fsh/omrs-encounter.fsh
Ticket Link: https://issues.openmrs.org/browse/FM2-519
> FM2-519: Created search parameters docs for the encounter Resource

- input/fsh/omrs-location.fsh
Issue Ticket: https://issues.openmrs.org/browse/FM2-511
> FM2-511: FHIR IG Add missing Attributes In Location Resource

- input/fsh/omrs-serviceRequest.fsh
Ticket link: https://issues.openmrs.org/browse/FM2-515
> FM2-515: Modifications in the Service Request profile, then added serviceRequest search parameters

- input/fsh/omrs-person.fsh
Ticket Link: https://issues.openmrs.org/browse/FM2-516
> FM2-516: Added search parameters onto the person resource

- input/fsh/omrs-patient.fsh
Ticket Link: https://issues.openmrs.org/browse/FM2-517
> FM2-517: Added search parameters onto the patient resource

- .gitignore
- input/fsh/omrs-location.fsh
- input/pagecontent/index.md
Ticket link: https://issues.openmrs.org/browse/FM2-525
> FM2-525: Customize IG homePage

- input/fsh/omrs-medicationDispense.fsh
Issue Link: https://issues.openmrs.org/browse/FM2-549
CC: @mozzy11
> FM2-549: FHIR IG MedicationDispense Resource

- input/fsh/omrs-immunization.fsh
- input/pagecontent/index.md
Issue Link:  https://issues.openmrs.org/browse/FM2-547
CC: @mozzy11
> FM2-547: Create FHIR IG Immunization Resource

- .gitignore
- input/fsh/omrs-allergyIntolerance.fsh
- input/fsh/omrs-condition.fsh
- input/fsh/omrs-diagnosticReport.fsh
- input/fsh/omrs-encounter.fsh
- input/fsh/omrs-group.fsh
- input/fsh/omrs-immunization.fsh
- input/fsh/omrs-location.fsh
- input/fsh/omrs-medication-request.fsh
- input/fsh/omrs-medication.fsh
- input/fsh/omrs-medicationDispense.fsh
- input/fsh/omrs-observation.fsh
- input/fsh/omrs-patient.fsh
- input/fsh/omrs-person.fsh
- input/fsh/omrs-practitioner.fsh
- input/fsh/omrs-serviceRequest.fsh
- input/fsh/omrs.task.fsh
- input/pagecontent/changes.md
- input/pagecontent/index.md
Ticket Link: https://issues.openmrs.org/browse/FM2-524
Removed Unsupported attributes which were carrying cardinality of 0..0 from all the Resources
> FM2-524: FHIR IG Remove unsupported attributes

- input/pagecontent/index.md
Follow up commit for https://issues.openmrs.org/browse/FM2-548
cc: @sherrif10 @abertnamanya
> FM2-548: Add medication resource to the index page

- input/fsh/omrs-related-person.fsh
- input/pagecontent/index.md
Add implementation guide for `RelatedPerson` - https://openmrs.atlassian.net/browse/FM2-550
> FM2-550 FHIR IG RelatedPerson Resource
